### ISSUE TITLE
什么时候给咱学校乐跑安排一下

### ISSUE THREAD

**Issue by Zhaofaksky** [MooWantFree/NwuDailyUp#1]

**Comment by MooWantFree** [comment]
已经毕业了, 没办法测试了.

**Comment by Zhaofaksky** [comment]
我很愿意配合大佬的😂
Duplicate of #

**Comment by MooWantFree** [comment]
> 我很愿意配合大佬的😂 Duplicate of #

最近看了一下, 这东西不root基本没法搞.
root之后可以用Fake location等工具, 不root就用Hackrf模拟发射gps信号.

**Comment by Zhaofaksky** [comment]
fake location那个作者更新有点跟不上乐跑的更新了，乐跑一更新可能就没用了。hackrf不是很懂，大佬有兴趣做吗，或者给个方向我自己去学着试着弄弄

**Comment by MooWantFree** [comment]
> fake location那个作者更新有点跟不上乐跑的更新了，乐跑一更新可能就没用了。hackrf不是很懂，大佬有兴趣做吗，或者给个方向我自己去学着试着弄弄

既然商业软件都跟不上他的更新，我就更不可能跟上了.
hackrf就是基于硬件的发射物理gps信号欺骗手机，全都是开源的，网上教程很多
